"use client";

import { useCallback, useEffect, useState, type FormEvent } from "react";
import { useAuth } from "./auth-shell";

type User={id:string;email:string;display_name:string;role:"analyst"|"admin";active:boolean;active_sessions:number;last_login_at?:string|null};
type Overview={users:{count:number;active:number;admins:number};sessions:Array<Record<string,string>>;journeys:Array<Record<string,string>>;runs:Array<{status:string;count:number}>;data:{referenced_source_bytes:number;referenced_source_files:number;run_byte_limit:number;object_limit:number;scanned_key_limit:number;disk_reserve_bytes:number;strategy:string[]};stack:Array<{name:string;service:string;state:string;connects_to:string[]}>;costs:{items:Array<{name:string;amount:number}>;total:number;note:string};apis:Array<{method:string;path:string;purpose:string}>};
type Capacity={storage:{free_bytes:number;reserve_bytes:number};jobs:{pending:number}};
const apiUrl=(process.env.NEXT_PUBLIC_API_URL??"").replace(/\/$/,"");
const size=(value:number)=>new Intl.NumberFormat("en-IN",{maximumFractionDigits:1}).format(value/1_000_000_000)+" GB";

export default function AdminOperations(){
 const {user}=useAuth();const [overview,setOverview]=useState<Overview|null>(null);const [capacity,setCapacity]=useState<Capacity|null>(null);const [users,setUsers]=useState<User[]>([]);const [tab,setTab]=useState("stack");const [error,setError]=useState("");const [form,setForm]=useState({email:"",display_name:"",password:"",role:"analyst"});
 const load=useCallback(async()=>{if(user.role!=="admin")return;const responses=await Promise.all([fetch(apiUrl+"/api/v1/admin/overview",{credentials:"include",cache:"no-store"}),fetch(apiUrl+"/api/v1/admin/users",{credentials:"include",cache:"no-store"}),fetch(apiUrl+"/api/v1/admin/capacity",{credentials:"include",cache:"no-store"})]);if(responses.some(response=>!response.ok))throw new Error("Administrator telemetry is unavailable.");setOverview(await responses[0].json() as Overview);setUsers(await responses[1].json() as User[]);setCapacity(await responses[2].json() as Capacity);},[user.role]);
 useEffect(()=>{load().catch(reason=>setError(reason instanceof Error?reason.message:"Unable to load"));},[load]);
 async function createUser(event:FormEvent){event.preventDefault();setError("");const response=await fetch(apiUrl+"/api/v1/admin/users",{method:"POST",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});const body=await response.json().catch(()=>({detail:"Unable to create user"})) as {detail?:string};if(!response.ok){setError(body.detail??"Unable to create user");return;}setForm({email:"",display_name:"",password:"",role:"analyst"});await load();}
 async function updateUser(target:User,patch:{role?:string;active?:boolean}){setError("");const response=await fetch(apiUrl+"/api/v1/admin/users/"+target.id,{method:"PATCH",credentials:"include",headers:{"Content-Type":"application/json"},body:JSON.stringify(patch)});const body=await response.json().catch(()=>({detail:"Unable to update user"})) as {detail?:string};if(!response.ok){setError(body.detail??"Unable to update user");return;}await load();}
 if(user.role!=="admin")return <section className="adminPanel" id="admin"><div className="permissionCard"><span>ADMIN WORKSPACE</span><h2>Administrator access required</h2><p>Ask an administrator if your role needs to change.</p></div></section>;
 const tabs=["stack","cost","apis","data","users","sessions","journeys"];
 return <section className="adminPanel" id="admin">
  <div className="sectionHeading"><div><p className="eyebrow">ADMINISTRATOR WORKSPACE</p><h2>System, access and usage</h2></div><button className="refreshButton" onClick={()=>load().catch(()=>setError("Refresh failed"))}>Refresh live data</button></div>
  {error&&<div className="formError" role="alert">{error}</div>}
  <div className="adminStats"><article><span>Active users</span><strong>{overview?.users.active??"—"}</strong><small>{overview?.users.admins??0} administrators</small></article><article><span>Live sessions</span><strong>{overview?.sessions.length??"—"}</strong><small>12-hour maximum</small></article><article><span>Disk free</span><strong>{capacity?size(capacity.storage.free_bytes):"—"}</strong><small>{capacity?size(capacity.storage.reserve_bytes):"—"} protected</small></article><article><span>Queue pending</span><strong>{capacity?.jobs.pending??"—"}</strong><small>One worker</small></article></div>
  <div className="adminTabs" role="tablist">{tabs.map(item=><button key={item} className={tab===item?"selected":""} onClick={()=>setTab(item)}>{item}</button>)}</div>
  {tab==="stack"&&<div className="stackMap">{overview?.stack.map((item,index)=><article key={item.name}><div><span>{String(index+1).padStart(2,"0")}</span><i/></div><h3>{item.name}</h3><strong>{item.service}</strong><p>Connects to {item.connects_to.join(", ")}</p></article>)}</div>}
  {tab==="cost"&&<div className="costPanel"><div><p className="eyebrow">MONTHLY ESTIMATE</p><strong className="costTotal">{"$"+(overview?.costs.total.toFixed(2)??"—")}</strong><span>USD · supplied by DevOps</span></div><div>{overview?.costs.items.map(item=><p key={item.name}><span>{item.name}</span><strong>{"$"+item.amount.toFixed(2)}</strong></p>)}<small>{overview?.costs.note}</small></div></div>}
  {tab==="apis"&&<div className="apiTable"><div className="apiRow apiHeader"><span>Method</span><span>Endpoint</span><span>Purpose</span></div>{overview?.apis.map(item=><div className="apiRow" key={item.path}><strong>{item.method}</strong><code>{item.path}</code><span>{item.purpose}</span></div>)}</div>}
  {tab==="data"&&overview&&<div className="dataGrid"><article><span>Referenced source</span><strong>{size(overview.data.referenced_source_bytes)}</strong><small>{overview.data.referenced_source_files} objects · source files are not retained</small></article><article><span>Per-run ceiling</span><strong>{size(overview.data.run_byte_limit)}</strong><small>{overview.data.object_limit.toLocaleString()} objects maximum</small></article><article><span>Scan guard</span><strong>{overview.data.scanned_key_limit.toLocaleString()}</strong><small>Keys before fail-closed stop</small></article><div className="strategyList"><h3>Optimization strategy</h3>{overview.data.strategy.map(item=><p key={item}>✓ {item}</p>)}</div></div>}
  {tab==="users"&&<div className="userWorkspace"><form className="userCreate" onSubmit={createUser}><h3>Add a team member</h3><label>Name<input value={form.display_name} onChange={event=>setForm({...form,display_name:event.target.value})} required/></label><label>Email<input type="email" value={form.email} onChange={event=>setForm({...form,email:event.target.value})} required/></label><label>Temporary password<input type="password" minLength={12} value={form.password} onChange={event=>setForm({...form,password:event.target.value})} required/></label><label>Role<select value={form.role} onChange={event=>setForm({...form,role:event.target.value})}><option value="analyst">Analyst</option><option value="admin">Administrator</option></select></label><button>Add user</button><small>Only the password hash is stored.</small></form><div className="userList">{users.map(item=><article key={item.id} className={!item.active?"disabledUser":""}><div><span className="avatar">{item.display_name.slice(0,2).toUpperCase()}</span><div><strong>{item.display_name}</strong><small>{item.email}</small></div></div><p>{item.active_sessions} active sessions · {item.last_login_at?"Last login "+new Date(item.last_login_at).toLocaleString():"Never signed in"}</p><div><button onClick={()=>updateUser(item,{role:item.role==="admin"?"analyst":"admin"})}>{item.role==="admin"?"Make analyst":"Make admin"}</button><button className="dangerButton" disabled={item.id===user.id} onClick={()=>updateUser(item,{active:!item.active})}>{item.active?"Remove access":"Restore access"}</button></div></article>)}</div></div>}
  {tab==="sessions"&&<div className="sessionTable"><div className="sessionRow sessionHeader"><span>User</span><span>Role</span><span>Signed in</span><span>Last activity</span><span>Expires</span></div>{overview?.sessions.map(item=><div className="sessionRow" key={item.id}><span><strong>{item.display_name}</strong><small>{item.email}</small></span><span>{item.role}</span><span>{new Date(item.created_at).toLocaleString()}</span><span>{new Date(item.last_seen_at).toLocaleString()}</span><span>{new Date(item.expires_at).toLocaleString()}</span></div>)}</div>}
  {tab==="journeys"&&<div className="journeyList">{overview?.journeys.map((item,index)=><article key={index}><span className={item.result==="success"||item.result==="accepted"?"journeyOk":"journeyNeutral"}/><div><strong>{item.actor}</strong><p>{item.action.replaceAll("."," → ").replaceAll("_"," ")}</p></div><small>{new Date(item.created_at).toLocaleString()}</small></article>)}</div>}
 </section>;
}
